### ISSUE TITLE
FlightUnavailableError whenever trying to connect to Neo4j server with python driver

### ISSUE THREAD

**Issue by emigre459** [neo4j-field/neo4j-arrow#4]
Specs (on client machine):

* neo4j-arrow=v4
* pyarrow=6.0.1
* python=3.9.7
* OS is Ubuntu

Specs (on server):

* neo4j=4.4.2
* OS is Amazon Linux 2

I'm using a remote Neo4j instance (HTTPS setup) on an Amazon EC2 instance that I can connect to without issue with the native Neo4j driver. I pulled down the `neo4j_arrow.py` file from this repo and put it into use inside a module of my package so I could access it similar to a traditionally installed package. However, whenever I try to submit a ticket, I always get the error `FlightUnavailableError: gRPC returned unavailable error, with message: failed to connect to all addresses`. Setting up the client does not error out.

I've pushed the v4 JAR into my database plugins directory and restarted Neo4j, as well as opened up port 9999 on the EC2 instance, so that shouldn't be an issue. Note that I have a DNS type A record redirecting from the IP to a human-friendly-named subdomain we control.

Here is the code I'm attempting to run from a Jupyter notebook:

```
import neo4j_arrow as na
client = na.Neo4jArrow(
    user='neo4j', 
    password=<my_password>, 
    location=('mygraph.mycompany.com', 9999)
)
ticket = client.cypher(query) # Errors out here
client.stream(ticket).read_all().to_pandas().info()
```

Any thoughts on what could be the problem?

**Comment by voutilad** [comment]
Can you try using something like [netcat](https://www.tecmint.com/check-remote-port-in-linux/) to confirm you can connect from the client machine to the remote neo4j-arrow service? This will at least rule out networking issues.

The `Neo4jArrow` client only connects to the service when needed, so you should always be able to create an instance. The behavior you see where it only raises an exception when you use the client is expected.

**Comment by cpuwar** [comment]
I got the same issue with emigre above. I am testing with neo4j server and jupyter on the same machine.
< netcat test >
echo "hello" | nc localhost 9999
���bHTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 68656c6c6f0a
< neo4j server log >
2022-02-13 10:41:14.564+0000 INFO  ======== Neo4j 4.4.4 ========
2022-02-13 10:41:14.587+0000 INFO  >>>--[Arrow]--> init()
[2022-02-13T19:41:14:589] [main] INFO org.apache.arrow.memory.BaseAllocator - Debug mode disabled.
[2022-02-13T19:41:14:590] [main] INFO org.apache.arrow.memory.DefaultAllocationManagerOption - allocation manager type not specified, using netty as the default type
[2022-02-13T19:41:14:590] [main] INFO org.apache.arrow.memory.CheckAllocator - Using DefaultAllocationManager at memory/DefaultAllocationManagerFactory.class
2022-02-13 10:41:18.684+0000 INFO  >>>--[Arrow]--> start()
[2022-02-13T19:41:18:695] [main] INFO org.neo4j.arrow.App - server listening @ grpc+tcp://localhost:9999
2022-02-13 10:41:18.695+0000 INFO  started arrow app at location Location{uri=grpc+tcp://localhost:9999}
2022-02-13 10:41:18.696+0000 INFO  Sending metrics to CSV file at /mnt/nvme/neo4j-enterprise-4.4.4/metrics
2022-02-13 10:41:18.712+0000 INFO  Bolt enabled on [0:0:0:0:0:0:0:0%0]:7687.
2022-02-13 10:41:19.254+0000 INFO  Remote interface available at http://localhost:7474/
2022-02-13 10:41:19.256+0000 INFO  id: 69E49C27460A89FA5231E40186C98308E23D473206C5DA0D261CBDBA01D2A7C5
2022-02-13 10:41:19.256+0000 INFO  name: system
2022-02-13 10:41:19.256+0000 INFO  creationDate: 2022-02-11T15:33:57.409Z
2022-02-13 10:41:19.257+0000 INFO  Started.
2022-02-13 10:55:44.079+0000 ERROR Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@5b467b55
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:619) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [neo4j-arrow-plugin-4.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.gds.compat.GraphDatabaseApiProxy
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more
2022-02-13 10:55:57.123+0000 ERROR Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@3b8eaa73
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:619) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [neo4j-arrow-plugin-4.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more
2022-02-13 11:12:06.202+0000 ERROR Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@57fc3e3a
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:619) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [neo4j-arrow-plugin-4.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more

**Comment by voutilad** [comment]
Did you install the Neo4j Graph Data Science Library (GDS) plugin as well?

**Comment by michael-smith-qs2** [comment]
Hi @[voutilad](https://github.com/voutilad) I am a colleague of @emigre459 's - to answer your questions:
- we are using Arrow plugin 4.0, apoc 4.4.0.1, Graph data science 1.8.1 . 
- In addition, here is the output of netstat, where the same java process is listening on port 7473, 7687, and 9999 - ostensibly https, bolt, and arrow, respectively. 
```
sudo netstat -plnt
tcp6       0      0 :::7687                 :::*                    LISTEN      15823/java
tcp6       0      0 127.0.0.1:9999          :::*                    LISTEN      15823/java
tcp6       0      0 :::7473                 :::*                    LISTEN      15823/java
```
What else might you need or suggest for us to try?
Thanks again for your help!

**Comment by voutilad** [comment]
It looks like you're binding to `127.0.0.1:9999`...which will not be exposed externally unless you do some additional networking.

Set the `HOST` environment variable to the ip/hostname or to `0.0.0.0` if you want it binding to all interfaces. See https://github.com/neo4j-field/neo4j-arrow/blob/main/README.md?plain=1#L69

**Comment by michael-smith-qs2** [comment]
Thanks - d'oh! good catch. Everything's good! Feel free to close.

**Comment by michael-smith-qs2** [comment]
Hi @voutilad , another hopefully-quick follow-up question relating to naivety about documented variables. I'm getting another`FlightUnavailableError` after setting the `ARROW_TLS_CERTIFICATE` and `ARROW_TLS_PRIVATE_KEY` env vars. I'm using the same public.crt and private.key that are used by the main Neo4j server process, by which our HTTPS connection is set up successfully. Do I need to generate a separate pair of files? Both files are in .pem format already, per [here](https://stackoverflow.com/a/991772). Thanks!
