### ISSUE TITLE
FlightServerError: Flight RPC failed with message:

### ISSUE THREAD

**Issue by cpuwar** [neo4j-field/neo4j-arrow#5]
I am testing with neo4j server 4.4.4 and jupyter on the same machine(ubuntu 20.04.3).
I use the same code(I copied it into python folder to import neo4j_arrow.py) :
https://github.com/neo4j-field/neo4j-arrow/blob/main/examples/PyArrow%20Demo.ipynb

I passed this with no error:
client = neo4j_arrow.Neo4jArrow('neo4j', '1234',
                                ('localhost', 9999), False, True)

But I got error at the next step:
actions = client.list_actions()
for action in actions:
  print(action)

FlightServerError                         Traceback (most recent call last)
<ipython-input-27-2982b2133982> in <module>
----> 1 actions = client.list_actions()
      2 
      3 for action in actions:
      4   print(action)

~/jupyter/neo4j-arrow/python/neo4j_arrow.py in list_actions(self)
    134         :return: list of all available Actions
    135         """
--> 136         return list(self._client.list_actions(self._options))
    137 
    138     def list_flights(self) -> List[flight.FlightInfo]:

~/jupyter/lib/python3.8/site-packages/pyarrow/_flight.pyx in pyarrow._flight.FlightClient.list_actions()

~/jupyter/lib/python3.8/site-packages/pyarrow/_flight.pyx in pyarrow._flight.FlightClient.list_actions()

~/jupyter/lib/python3.8/site-packages/pyarrow/_flight.pyx in pyarrow._flight.check_flight_status()

FlightServerError: Flight RPC failed with message: 

< neo4j server log >
2022-02-13 12:53:46.404+0000 INFO  This instance is ServerId{1a293e6d} (1a293e6d-f075-4f27-806d-9ea784f4c08a)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/nvme/neo4j-enterprise-4.4.4/plugins/neo4j-arrow-plugin-4.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/nvme/neo4j-enterprise-4.4.4/lib/slf4j-nop-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
2022-02-13 12:53:47.181+0000 INFO  ======== Neo4j 4.4.4 ========
2022-02-13 12:53:47.206+0000 INFO  >>>--[Arrow]--> init()
[2022-02-13T21:53:47:207] [main] INFO org.apache.arrow.memory.BaseAllocator - Debug mode disabled.
[2022-02-13T21:53:47:208] [main] INFO org.apache.arrow.memory.DefaultAllocationManagerOption - allocation manager type not specified, using netty as the default type
[2022-02-13T21:53:47:209] [main] INFO org.apache.arrow.memory.CheckAllocator - Using DefaultAllocationManager at memory/DefaultAllocationManagerFactory.class
2022-02-13 12:53:51.174+0000 INFO  >>>--[Arrow]--> start()
[2022-02-13T21:53:51:187] [main] INFO org.neo4j.arrow.App - server listening @ grpc+tcp://localhost:9999
2022-02-13 12:53:51.188+0000 INFO  started arrow app at location Location{uri=grpc+tcp://localhost:9999}
2022-02-13 12:53:51.189+0000 INFO  Sending metrics to CSV file at /mnt/nvme/neo4j-enterprise-4.4.4/metrics
2022-02-13 12:53:51.208+0000 INFO  Bolt enabled on [0:0:0:0:0:0:0:0%0]:7687.
2022-02-13 12:53:51.792+0000 INFO  Remote interface available at http://localhost:7474/
2022-02-13 12:53:51.794+0000 INFO  id: 69E49C27460A89FA5231E40186C98308E23D473206C5DA0D261CBDBA01D2A7C5
2022-02-13 12:53:51.794+0000 INFO  name: system
2022-02-13 12:53:51.794+0000 INFO  creationDate: 2022-02-11T15:33:57.409Z
2022-02-13 12:53:51.794+0000 INFO  Started.

**Comment by cpuwar** [comment]
Found the error logs in neo4j server:
2022-02-13 13:57:15.745+0000 ERROR Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@2f1f0a35
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:619) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [neo4j-arrow-plugin-4.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/neo4j/gds/compat/GraphDatabaseApiProxy
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.gds.compat.GraphDatabaseApiProxy
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at org.neo4j.arrow.ArrowService.lambda$init$6(ArrowService.java:97) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.neo4j.arrow.auth.NativeAuthValidator.validate(NativeAuthValidator.java:106) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.BasicCallHeaderAuthenticator.authenticate(BasicCallHeaderAuthenticator.java:60) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:50) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.auth2.ServerCallHeaderAuthMiddleware$Factory.onCallStarted(ServerCallHeaderAuthMiddleware.java:36) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at org.apache.arrow.flight.grpc.ServerInterceptorAdapter.interceptCall(ServerInterceptorAdapter.java:94) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615) ~[neo4j-arrow-plugin-4.0-all.jar:?]
	... 6 more

**Comment by cpuwar** [comment]
I solved the problem by copying gds jar into plugin folder even though not using it.

**Comment by voutilad** [comment]
Yes, GDS is required as a dependency. https://github.com/neo4j-field/neo4j-arrow/blob/main/README.md?plain=1#L48-L50
